"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { supabase } from "../lib/supabase";
import { WorkerRosterImport } from "./WorkerRosterImport";

export type AdminTeam = { id:string; team_code:string; leader_name:string; is_active:boolean };
export type AdminWorker = { id:string; mnv:string; full_name:string; job_title:string|null; team_id:string|null; stt_in_team:number|null };
type PayrollRow = { team_id:string;team_name:string;role_name:string;worker_count:number;average_monthly:number;average_daily:number;total_daily:number;total_monthly:number;status:string;unknown_workers:Array<{mnv:string;full_name:string;job_title:string}> };
type AppUser = { profile_id:string;auth_user_id:string;email:string;display_name:string|null;role_code:string;is_active:boolean;worker_id:string|null;team_ids:string[];note:string|null;last_sign_in_at:string|null };

const money = new Intl.NumberFormat("vi-VN",{style:"currency",currency:"VND",maximumFractionDigits:0});
const roleNames:Record<string,string>={ADMIN:"Quản trị viên",GIAM_SAT:"Giám sát",TO_TRUONG:"Tổ trưởng",NHAN_VIEN:"Nhân viên",XEM:"Chỉ xem"};

export function WorkersAdminPanel({teams,workers,canEdit,onChanged,notify}:{teams:AdminTeam[];workers:AdminWorker[];canEdit:boolean;onChanged:()=>Promise<void>;notify:(text:string)=>void}){
  const empty={id:"",mnv:"",full_name:"",job_title:"",team_id:teams.find(t=>t.is_active)?.id||"",stt_in_team:""};
  const [form,setForm]=useState(empty),[saving,setSaving]=useState(false),[payroll,setPayroll]=useState<PayrollRow[]>([]),[payrollError,setPayrollError]=useState("");
  async function loadPayroll(){const {data,error}=await supabase.rpc("get_payroll_summary",{p_team_id:null});if(error){setPayrollError(error.message);return;}setPayroll((data||[]) as PayrollRow[]);setPayrollError("");}
  useEffect(()=>{let active=true;void supabase.rpc("get_payroll_summary",{p_team_id:null}).then(({data,error})=>{if(!active)return;if(error){setPayrollError(error.message);return;}setPayroll((data||[]) as PayrollRow[]);setPayrollError("")});return()=>{active=false}},[]);
  const byTeam=useMemo(()=>new Map(teams.map(team=>[team.id,payroll.filter(row=>row.team_id===team.id)])),[teams,payroll]);
  async function save(event:FormEvent){event.preventDefault();if(saving)return;setSaving(true);const {error}=await supabase.rpc("admin_save_worker",{p_worker_id:form.id||null,p_mnv:form.mnv,p_full_name:form.full_name,p_job_title:form.job_title||null,p_team_id:form.team_id,p_stt_in_team:form.stt_in_team?Number(form.stt_in_team):null});setSaving(false);if(error){notify(error.message);return;}setForm({...empty,team_id:form.team_id});notify(form.id?"Đã cập nhật công nhân.":"Đã thêm công nhân.");await onChanged();await loadPayroll();}
  function edit(worker:AdminWorker){setForm({id:worker.id,mnv:worker.mnv,full_name:worker.full_name,job_title:worker.job_title||"",team_id:worker.team_id||"",stt_in_team:worker.stt_in_team?.toString()||""});window.scrollTo({top:0,behavior:"smooth"});}
  async function archive(worker:AdminWorker){if(!window.confirm(`Ngừng sử dụng công nhân ${worker.mnv} - ${worker.full_name}?`))return;const {error}=await supabase.rpc("admin_archive_worker",{p_worker_id:worker.id});if(error){notify(error.message);return;}notify("Đã ngừng sử dụng công nhân; lịch sử được giữ nguyên.");await onChanged();await loadPayroll();}
  return <>
    {canEdit&&<WorkerRosterImport teams={teams} onChanged={async()=>{await onChanged();await loadPayroll()}} notify={notify}/>}
    {canEdit&&<div className="card"><div className="card-header"><span className="ch-icon">👷</span><span className="ch-title">{form.id?"Sửa công nhân":"Thêm công nhân"}</span></div><form className="card-body" onSubmit={save}><div className="form-row"><label className="form-group"><span>Mã nhân viên (MNV)</span><input className="form-control" value={form.mnv} onChange={e=>setForm({...form,mnv:e.target.value})} required/></label><label className="form-group"><span>Họ và tên</span><input className="form-control" value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})} required/></label></div><div className="form-row"><label className="form-group"><span>Chức vụ gốc (dùng nhận diện Hệ/Bậc)</span><input className="form-control" value={form.job_title} onChange={e=>setForm({...form,job_title:e.target.value})} placeholder="Ví dụ: Thợ Điện bậc 2"/></label><label className="form-group"><span>Tổ</span><select className="form-control" value={form.team_id} onChange={e=>setForm({...form,team_id:e.target.value})} required>{teams.filter(t=>t.is_active).map(t=><option key={t.id} value={t.id}>{t.leader_name}</option>)}</select></label><label className="form-group"><span>STT trong Tổ</span><input className="form-control" type="number" min="1" value={form.stt_in_team} onChange={e=>setForm({...form,stt_in_team:e.target.value})}/></label></div><div className="form-actions">{form.id&&<button type="button" className="btn btn-secondary" onClick={()=>setForm(empty)}>Hủy sửa</button>}<button className="btn btn-primary" disabled={saving}>{saving?"Đang lưu…":"Lưu công nhân"}</button></div></form></div>}
    <div className="card"><div className="card-header"><span className="ch-icon">👥</span><span className="ch-title">Danh sách công nhân ({workers.length})</span><span className="badge badge-cyan">Nguồn Supabase</span></div><div className="card-body table-wrap"><table><thead><tr><th>MNV</th><th>Họ tên</th><th>Chức vụ</th><th>Tổ</th><th>STT</th>{canEdit&&<th>Thao tác</th>}</tr></thead><tbody>{workers.map(w=><tr key={w.id}><td><strong>{w.mnv}</strong></td><td>{w.full_name}</td><td>{w.job_title||"Chưa xác định"}</td><td>{teams.find(t=>t.id===w.team_id)?.leader_name||"Chưa gán"}</td><td>{w.stt_in_team||"—"}</td>{canEdit&&<td><button className="btn btn-sm btn-secondary" onClick={()=>edit(w)}>Sửa</button> <button className="btn btn-sm btn-red" onClick={()=>archive(w)}>Ngừng dùng</button></td>}</tr>)}</tbody></table></div></div>
    <div className="section-divider"><span>Quỹ lương tự động theo từng MNV</span></div>{payrollError&&<div className="toast error static-toast">{payrollError}</div>}<div className="payroll-grid">{teams.filter(t=>t.is_active).map(team=>{const rows=byTeam.get(team.id)||[],unknown=(rows[0]?.unknown_workers||[]);return <article className="payroll-card" key={team.id}><div className="payroll-title"><strong>{team.leader_name}</strong><span>{workers.filter(w=>w.team_id===team.id).length} CNCH</span></div><div className="grade-list">{rows.map(row=><div key={row.role_name}><span>{row.role_name}</span><b>{row.worker_count} · {money.format(Number(row.total_daily))}/ngày</b></div>)}</div><div className="payroll-total"><span>Tổng quỹ lương ngày</span><strong>{money.format(rows.reduce((sum,row)=>sum+Number(row.total_daily),0))}</strong></div>{unknown.length>0&&<div className="login-error">{unknown.length} CNCH chưa xác định Hệ/Bậc: {unknown.map(x=>x.mnv).join(", ")}</div>}</article>})}</div>
  </>;
}

export function UsersAdminPanel({teams,workers,notify}:{teams:AdminTeam[];workers:AdminWorker[];notify:(text:string)=>void}){
  const blank={auth_user_id:"",email:"",password:"",display_name:"",role_code:"XEM",is_active:true,worker_id:"",team_ids:[] as string[],note:""};
  const [users,setUsers]=useState<AppUser[]>([]),[form,setForm]=useState(blank),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState("");
  async function request(method="GET",body?:unknown){const {data}=await supabase.auth.getSession();const token=data.session?.access_token;if(!token)throw new Error("Phiên đăng nhập đã hết hạn.");const response=await fetch("/api/admin/users",{method,headers:{Authorization:`Bearer ${token}`,...(body?{"Content-Type":"application/json"}:{})},body:body?JSON.stringify(body):undefined});const result=await response.json();if(!response.ok)throw new Error(result.error||"Không thể quản lý người dùng.");return result;}
  async function load(){setLoading(true);try{const result=await request();setUsers(result.users||[]);setError("");}catch(e){setError(e instanceof Error?e.message:"Lỗi tải người dùng");}finally{setLoading(false)}}
  useEffect(()=>{let active=true;void request().then(result=>{if(!active)return;setUsers(result.users||[]);setError("")}).catch(error=>{if(active)setError(error instanceof Error?error.message:"Lỗi tải người dùng")}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[]);
  function edit(user:AppUser){setForm({auth_user_id:user.auth_user_id,email:user.email,password:"",display_name:user.display_name||"",role_code:user.role_code,is_active:user.is_active,worker_id:user.worker_id||"",team_ids:user.team_ids||[],note:user.note||""});window.scrollTo({top:0,behavior:"smooth"});}
  function toggleTeam(id:string){setForm({...form,team_ids:form.team_ids.includes(id)?form.team_ids.filter(x=>x!==id):[...form.team_ids,id]});}
  async function save(event:FormEvent){event.preventDefault();if(saving)return;setSaving(true);try{await request(form.auth_user_id?"PATCH":"POST",{...form,worker_id:form.worker_id||null});notify(form.auth_user_id?"Đã cập nhật người dùng.":"Đã tạo tài khoản đăng nhập.");setForm(blank);await load();}catch(e){notify(e instanceof Error?e.message:"Không thể lưu người dùng");}finally{setSaving(false)}}
  return <><div className="card"><div className="card-header"><span className="ch-icon">🔐</span><span className="ch-title">{form.auth_user_id?"Sửa quyền người dùng":"Thêm người dùng"}</span><span className="badge badge-cyan">Supabase Auth + RPC</span></div><form className="card-body" onSubmit={save}><div className="form-row"><label className="form-group"><span>Email đăng nhập</span><input className="form-control" type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/></label><label className="form-group"><span>{form.auth_user_id?"Mật khẩu mới (để trống nếu giữ nguyên)":"Mật khẩu ban đầu"}</span><input className="form-control" type="password" minLength={8} required={!form.auth_user_id} value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label><label className="form-group"><span>Tên hiển thị</span><input className="form-control" value={form.display_name} onChange={e=>setForm({...form,display_name:e.target.value})} required/></label></div><div className="form-row"><label className="form-group"><span>Vai trò</span><select className="form-control" value={form.role_code} onChange={e=>setForm({...form,role_code:e.target.value})}>{Object.entries(roleNames).map(([code,label])=><option value={code} key={code}>{label}</option>)}</select></label><label className="form-group"><span>Gắn MNV (không bắt buộc)</span><select className="form-control" value={form.worker_id} onChange={e=>setForm({...form,worker_id:e.target.value})}><option value="">Không gắn công nhân</option>{workers.map(w=><option value={w.id} key={w.id}>{w.mnv} - {w.full_name}</option>)}</select></label><label className="form-group checkbox-line"><input type="checkbox" checked={form.is_active} onChange={e=>setForm({...form,is_active:e.target.checked})}/><span>Cho phép đăng nhập</span></label></div><div className="form-group"><span>Phạm vi Tổ</span><div className="team-scope-list">{teams.filter(t=>t.is_active).map(t=><label key={t.id} className="checkbox-line"><input type="checkbox" checked={form.team_ids.includes(t.id)} onChange={()=>toggleTeam(t.id)}/><span>{t.leader_name}</span></label>)}</div></div><label className="form-group"><span>Ghi chú</span><input className="form-control" value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/></label><div className="form-actions">{form.auth_user_id&&<button type="button" className="btn btn-secondary" onClick={()=>setForm(blank)}>Hủy sửa</button>}<button className="btn btn-primary" disabled={saving}>{saving?"Đang lưu…":"Lưu người dùng"}</button></div></form></div>
    <div className="card"><div className="card-header"><span className="ch-icon">👤</span><span className="ch-title">Tài khoản hệ thống ({users.length})</span></div><div className="card-body">{error&&<div className="toast error static-toast">{error}</div>}{loading?<div className="loading-text">Đang tải…</div>:<div className="user-list">{users.map(user=><button className="user-item user-item-button" key={user.auth_user_id} onClick={()=>edit(user)}><div className="user-avatar">{(user.display_name||user.email).slice(0,1).toUpperCase()}</div><div className="user-info"><div className="ui-name">{user.display_name||user.email}</div><div className="ui-email">{user.email}</div><div className="ui-meta">{roleNames[user.role_code]} · {(user.team_ids||[]).map(id=>teams.find(t=>t.id===id)?.leader_name).filter(Boolean).join(", ")||"Không giới hạn riêng"}</div></div><span className={`badge ${user.is_active?"badge-green":"badge-red"}`}>{user.is_active?"Đang hoạt động":"Đã khóa"}</span></button>)}</div>}</div></div></>;
}
