"use client";
/* eslint-disable react-hooks/exhaustive-deps */

import { useEffect, useState } from "react";
import { supabase } from "../lib/supabase";
import { DateInput } from "./DateInput";
import { downloadPgvCnchPdf, downloadPgvCommonPdf } from "../lib/downloadPgvPdf";
import { buildPgvDisplayRows } from "./pgvRows";

type Team={id:string;leader_name:string;is_active:boolean};
type Week={id:string;team_id:string;week_slot:number;start_date:string;end_date:string};
type PgvJob={id:string;content:string;location:string|null;quantity:number;unit:string|null;start_date:string;end_date:string;target_daily:number|null;count_leader:number;count_worker1:number;count_worker2:number;count_worker3:number;count_helper:number};
type Worker={id:string;mnv:string;full_name:string;job_title:string|null;stt_in_team:number|null};
type Assignment={worker_id:string;job_id:string|null;content_label:string|null;target:string|null;completed_qty:string|null};
type CnchData={project_name:string;week:Week;receive_date:string;assign_date:string;workers:Worker[];jobs:PgvJob[];assignments:Assignment[]};
const viDate=(value:string)=>{if(!/^\d{4}-\d{2}-\d{2}$/.test(value||""))return "—";const [y,m,d]=value.split("-");return `${d}/${m}/${y}`};
const people=(job:PgvJob)=>job.count_leader+job.count_worker1+job.count_worker2+job.count_worker3+job.count_helper;

function SheetHeader({title,projectName}:{title:string;projectName:string}){return <><h1 className="sheet-title">{title}</h1><div className="sheet-section-title">Thông tin chung</div><div className="sheet-info-grid"><div><b>Dự án:</b> {projectName}</div><div><b>Hạng mục:</b> Thi công cơ điện</div><div><b>Bên giao Việc:</b> Trung đoàn Cơ điện: ...02...; Tiểu đoàn ME: ...02.7...</div></div></>}
function Signatures(){return <div className="sheet-signatures"><div><b>Tiểu đội trưởng</b><i className="sign-hint">(ký, họ và tên)</i><span></span></div><div><b>Trung Đội Trưởng</b><i className="sign-hint">(ký, họ và tên)</i><span></span></div><div><b>Đại Đội Trưởng</b><i className="sign-hint">(ký, họ và tên)</i><span></span></div></div>}

function PgvCommonPrint({data}:{data:{team_name:string;project_name:string;assign_date:string;receive_date:string;worker_count:number;rows:PgvJob[]}}){return <section className="sheet-print pgv-sheet"><SheetHeader title="PHIẾU GIAO VIỆC" projectName={data.project_name}/><div className="sheet-two-col"><div><div><b>Bên nhận Việc:</b> {data.team_name}</div><div><b>Số CN:</b> {data.worker_count} công nhân</div><div><b>Ngày giao việc:</b> {viDate(data.assign_date)}</div><div><b>Ngày nhận việc:</b> {viDate(data.receive_date)}</div></div><div><b>Yêu cầu kèm theo:</b><div>- Kiểm soát tiến độ, vật tư, mặt bằng</div><div>- Kiểm soát tổ đội, nhân lực, giờ làm việc</div><div>- Kiểm soát ATLĐ, chất lượng, sản lượng</div><div>- Kiểm soát kho bãi</div><b>Tài liệu kèm theo:</b><div>- Bản vẽ phạm vi giao việc được duyệt (bắt buộc)</div></div></div><table className="sheet-table pgv-work">{/* Chiều ngang cố định theo cột. Bắt buộc dùng colgroup: hàng header đầu có colSpan nên với table-layout:fixed trình duyệt sẽ bỏ qua width đặt trên th/td. */}<colgroup><col className="c-stt"/><col className="c-pk"/><col className="c-lo"/><col className="c-block"/><col className="c-vitri"/><col className="c-noidung"/><col className="c-socn"/><col className="c-muctieu"/><col className="c-batdau"/><col className="c-ketthuc"/><col className="c-danhgia"/><col className="c-ghichu"/></colgroup><thead><tr><th rowSpan={2}>STT</th><th colSpan={5}>Nội dung công việc/Vị trí thực hiện</th><th rowSpan={2}>Số lượng CN</th><th rowSpan={2}>Mục tiêu hoàn thành<span className="th-hint">Mô tả ngắn gọn yêu cầu hoàn thành khối lượng bao nhiêu hoặc hoàn thành các công việc gì tương ứng với mốc thời gian của từng tuần</span></th><th colSpan={2}>Thời gian</th><th rowSpan={2}>Đánh giá kết quả hoàn thành</th><th rowSpan={2}>Ghi chú</th></tr><tr><th>Phân khu</th><th>Lô</th><th>Block</th><th>Vị trí chi tiết/tầng/mặt-trục</th><th>Nội dung công việc<span className="th-hint">Cần nêu rõ khối lượng nào tồn từ kỳ trước chưa hoàn thành, khối lượng nào giao mới</span></th><th>Ngày bắt đầu</th><th>Ngày kết thúc</th></tr></thead><tbody>{buildPgvDisplayRows(data.rows).map((job,index)=>job?<tr key={job.id}><td>{index+1}</td><td>{job.location||""}</td><td></td><td></td><td>{job.location||""}</td><td>{job.content}</td><td>{people(job)}</td><td>{job.quantity} {job.unit||""}</td><td>{viDate(job.start_date)}</td><td>{viDate(job.end_date)}</td><td></td><td></td></tr>:<tr key={`blank-${index}`}><td>{index+1}</td>{Array.from({length:11},(_,i)=><td key={i}></td>)}</tr>)}</tbody></table><div className="sheet-requirements"><div>- Y/c: Tuân thủ công tác an toàn, bảo hộ lao động; đảm bảo nhân lực và tiến độ cam kết.</div><div>- Y/c: Đảm bảo vệ sinh khu vực, thu gom vật tư thừa sau 01 ngày thi công.</div><div>- Y/c: Gửi đánh giá sản lượng/chất lượng hằng ngày trước 20:00; báo cáo tuần trước 11:00 thứ 5.</div><div>- Y/c: Không làm việc phát sinh khi chưa có chấp thuận của lãnh đạo.</div></div><Signatures/></section>}

function PgvCnchPrint({data,teamName,items}:{data:CnchData;teamName:string;items:Record<string,Assignment>}){return <section className="sheet-print pgvcnch-sheet"><SheetHeader title="PHIẾU GIAO VIỆC CÔNG NHÂN CƠ HỮU HẰNG NGÀY" projectName={data.project_name}/><div className="sheet-info-grid"><div><b>Bên nhận Việc:</b> {teamName}</div><div><b>Ngày giao việc:</b> {viDate(data.assign_date)}</div><div><b>Ngày nhận việc:</b> {viDate(data.receive_date)} · Tuần {data.week.week_slot}</div></div><table className="sheet-table"><thead><tr><th>STT</th><th>Ngày bắt đầu</th><th>Ngày kết thúc</th><th>Khối lượng theo đầu việc</th><th>Mục tiêu/ngày</th><th>Hạng mục thi công gộp theo mã nhóm</th><th>SL Tổ trưởng</th><th>SL Thợ bậc 1</th><th>SL Thợ bậc 2</th><th>SL Thợ bậc 3</th><th>SL Thợ phụ</th></tr></thead><tbody>{data.jobs.map((job,index)=><tr key={job.id}><td>{index+1}</td><td>{viDate(job.start_date)}</td><td>{viDate(job.end_date)}</td><td>{job.quantity} {job.unit||""}</td><td>{job.target_daily??""} {job.unit||""}/ngày</td><td>{job.content}</td><td>{job.count_leader}</td><td>{job.count_worker1}</td><td>{job.count_worker2}</td><td>{job.count_worker3}</td><td>{job.count_helper}</td></tr>)}</tbody></table><table className="sheet-table cnch-workers"><thead><tr><th>STT</th><th>HỌ VÀ TÊN</th><th>MNV</th><th>CHỨC VỤ</th><th>NỘI DUNG CÔNG VIỆC</th><th>MỤC TIÊU HOÀN THÀNH</th><th>VỊ TRÍ THI CÔNG</th><th>KÝ TÊN</th><th>KHỐI LƯỢNG HOÀN THÀNH THỰC TẾ</th></tr></thead><tbody>{data.workers.map((worker,index)=>{const item=items[worker.id];const job=data.jobs.find(j=>j.id===item?.job_id);return <tr key={worker.id}><td>{index+1}</td><td>{worker.full_name}</td><td>{worker.mnv}</td><td>{worker.job_title||""}</td><td>{job?.content||"OFF"}</td><td>{item?.target||""}</td><td>{job?.location||""}</td><td></td><td>{item?.completed_qty||""}</td></tr>})}</tbody></table><Signatures/></section>}

export function PgvCommonRpc({teams,weeks,teamId,setTeamId,weekId,setWeekId,notify}:{teams:Team[];weeks:Week[];teamId:string;setTeamId:(id:string)=>void;weekId:string;setWeekId:(id:string)=>void;notify:(text:string)=>void}){
  const [data,setData]=useState<{team_name:string;project_name:string;assign_date:string;receive_date:string;worker_count:number;rows:PgvJob[]}|null>(null),[loading,setLoading]=useState(false);const available=weeks.filter(w=>w.team_id===teamId),effective=weekId||available[0]?.id||"";
  useEffect(()=>{if(!teamId||!effective)return;let active=true;void supabase.rpc("get_pgv_common",{p_team_id:teamId,p_week_id:effective}).then(({data:result,error})=>{if(!active)return;setLoading(false);if(error){notify(error.message);setData(null)}else setData(result as typeof data)});return()=>{active=false}},[teamId,effective]);
  return <><div className="card no-print"><div className="card-body filters-row"><select className="form-control" value={teamId} onChange={e=>{setTeamId(e.target.value);setWeekId("")}}><option value="">Chọn Tổ</option>{teams.filter(t=>t.is_active).map(t=><option key={t.id} value={t.id}>{t.leader_name}</option>)}</select><select className="form-control" value={effective} onChange={e=>setWeekId(e.target.value)}><option value="">Chọn Tuần</option>{available.map(w=><option key={w.id} value={w.id}>Tuần {w.week_slot}: {viDate(w.start_date)}–{viDate(w.end_date)}</option>)}</select><button className="btn btn-primary" disabled={!data} onClick={()=>window.print()}>🖨️ In phiếu</button><button className="btn btn-secondary" disabled={!data} onClick={()=>data&&void downloadPgvCommonPdf(data)}>⬇️ Tải PDF</button></div></div>{loading&&<div className="loading-text">Đang lấy dữ liệu phiếu…</div>}{data?<PgvCommonPrint data={data}/>:<div className="empty-state"><div className="es-icon">📄</div><div className="es-title">Chọn đúng Tổ và Tuần để lấy Phiếu giao việc</div></div>}</>;
}

export function PgvCnchRpc({teams,teamId,setTeamId,receiveDate,setReceiveDate,canEdit,notify}:{teams:Team[];teamId:string;setTeamId:(id:string)=>void;receiveDate:string;setReceiveDate:(date:string)=>void;canEdit:boolean;notify:(text:string)=>void}){
  const [data,setData]=useState<CnchData|null>(null),[items,setItems]=useState<Record<string,Assignment>>({}),[loading,setLoading]=useState(false),[saving,setSaving]=useState(false);
  async function load(){if(!teamId||!receiveDate){setData(null);return}setLoading(true);const {data:result,error}=await supabase.rpc("get_pgv_cnch",{p_team_id:teamId,p_receive_date:receiveDate});setLoading(false);if(error){setData(null);notify(error.message);return}const next=result as CnchData;setData(next);const map:Record<string,Assignment>={};next.workers.forEach(w=>{map[w.id]=next.assignments.find(a=>a.worker_id===w.id)||{worker_id:w.id,job_id:null,content_label:null,target:"",completed_qty:""}});setItems(map)}
  useEffect(()=>{if(!teamId||!receiveDate)return;let active=true;void supabase.rpc("get_pgv_cnch",{p_team_id:teamId,p_receive_date:receiveDate}).then(({data:result,error})=>{if(!active)return;setLoading(false);if(error){setData(null);notify(error.message);return}const next=result as CnchData;setData(next);const map:Record<string,Assignment>={};next.workers.forEach(w=>{map[w.id]=next.assignments.find(a=>a.worker_id===w.id)||{worker_id:w.id,job_id:null,content_label:null,target:"",completed_qty:""}});setItems(map)});return()=>{active=false}},[teamId,receiveDate]);function patch(id:string,value:Partial<Assignment>){setItems(current=>({...current,[id]:{...current[id],...value}}))}
  async function save(){if(!data||saving)return;setSaving(true);const payload=data.workers.map(w=>{const item=items[w.id],job=data.jobs.find(j=>j.id===item?.job_id);return {...item,worker_id:w.id,job_id:item?.job_id||null,content_label:job?.content||"OFF"}});const {error}=await supabase.rpc("save_pgv_cnch_assignments",{p_request_key:crypto.randomUUID(),p_team_id:teamId,p_receive_date:receiveDate,p_items:payload});setSaving(false);if(error){notify(error.message);return}notify("Đã lưu phân công CNCH đúng Tổ và Tuần.");await load()}
  return <><div className="card no-print"><div className="card-body filters-row"><select className="form-control" value={teamId} onChange={e=>setTeamId(e.target.value)}><option value="">Chọn Tổ</option>{teams.filter(t=>t.is_active).map(t=><option key={t.id} value={t.id}>{t.leader_name}</option>)}</select><DateInput value={receiveDate} onChange={setReceiveDate}/>{canEdit&&<button className="btn btn-green" disabled={!data||saving} onClick={save}>{saving?"Đang lưu…":"Lưu phân công"}</button>}<button className="btn btn-primary" disabled={!data} onClick={()=>window.print()}>🖨️ In phiếu</button><button className="btn btn-secondary" disabled={!data} onClick={()=>data&&void downloadPgvCnchPdf(data,teams.find(t=>t.id===teamId)?.leader_name||"",items)}>⬇️ Tải PDF</button></div></div>{loading&&<div className="loading-text">Đang xác định Tuần và tải phân công…</div>}{data?<><div className="card no-print"><div className="card-body table-wrap"><table><thead><tr><th>MNV</th><th>Họ tên CNCH</th><th>Phân công</th><th>Mục tiêu</th><th>Khối lượng thực tế</th></tr></thead><tbody>{data.workers.map(w=>{const item=items[w.id]||{} as Assignment;return <tr key={w.id}><td>{w.mnv}</td><td>{w.full_name}</td><td><select className="form-control" disabled={!canEdit} value={item.job_id||""} onChange={e=>patch(w.id,{job_id:e.target.value||null})}><option value="">OFF</option>{data.jobs.map(j=><option key={j.id} value={j.id}>{j.content}</option>)}</select></td><td><input className="form-control" disabled={!canEdit} value={item.target||""} onChange={e=>patch(w.id,{target:e.target.value})}/></td><td><input className="form-control" disabled={!canEdit} value={item.completed_qty||""} onChange={e=>patch(w.id,{completed_qty:e.target.value})}/></td></tr>})}</tbody></table></div></div><PgvCnchPrint data={data} teamName={teams.find(t=>t.id===teamId)?.leader_name||""} items={items}/></>:<div className="empty-state"><div className="es-icon">👷</div><div className="es-title">Ngày nhận việc không thuộc Tuần đang hoạt động của Tổ</div></div>}</>;
}
