"use client";

import { useState } from "react";
import { supabase } from "../lib/supabase";
import { CnchWorkbook, parseCnchWorkbook, sha256Hex } from "../lib/cnchWorkbook";
import { rosterImportError } from "./importErrors";

type Team={leader_name:string;is_active:boolean};

export function WorkerRosterImport({onChanged,notify}:{teams?:Team[];onChanged:()=>Promise<void>;notify:(text:string)=>void}){
  const [file,setFile]=useState<File|null>(null),[preview,setPreview]=useState<CnchWorkbook|null>(null),[hash,setHash]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
  async function inspect(next:File|null){setFile(next);setPreview(null);setHash("");setError("");if(!next)return;setBusy(true);try{const [parsed,digest]=await Promise.all([parseCnchWorkbook(next),sha256Hex(next)]);setPreview(parsed);setHash(digest)}catch(e){setError(e instanceof Error?e.message:"Không đọc được file Excel.")}finally{setBusy(false)}}
  async function commit(){if(!file||!preview||busy)return;if(!window.confirm(`Thay danh sách hiện tại bằng ${preview.workers.length} công nhân thuộc ${preview.teams.length} tổ?\n\nCác Tổ mới trong Excel sẽ được tự động tạo. Hệ thống chỉ ghi khi toàn bộ file hợp lệ.`))return;setBusy(true);const active=preview.teams;const {data,error:rpcError}=await supabase.rpc("admin_import_worker_roster_v2",{p_request_key:crypto.randomUUID(),p_source_name:file.name,p_source_sha256:hash,p_workers:preview.workers,p_active_team_names:active});setBusy(false);if(rpcError){setError(rosterImportError(rpcError.message));notify("Nhập Excel thất bại; dữ liệu cũ được giữ nguyên.");return;}const result=data as {worker_count:number;team_count:number;active_team_count:number};notify(`Đã cập nhật ${result.worker_count} công nhân, ${result.team_count} tổ; còn ${result.active_team_count} tổ hoạt động.`);setFile(null);setPreview(null);setHash("");await onChanged()}
  return <div className="card"><div className="card-header"><span className="ch-icon">📥</span><span className="ch-title">Cập nhật danh sách công nhân bằng Excel</span><span className="badge badge-cyan">Chỉ Admin</span></div><div className="card-body"><p className="import-help">File .xlsx cần có 5 cột: Mã nhân viên, Họ và tên, Chức vụ, Tên Tổ, Dự án. Tổ mới trong file được tự động thêm; nếu có lỗi, toàn bộ dữ liệu cũ được giữ nguyên.</p><a className="btn btn-secondary roster-template" href="/Mau_Danh_Sach_CNCH.xlsx" download>⬇️ Tải mẫu Excel chuẩn</a><input className="form-control" type="file" accept=".xlsx" disabled={busy} onChange={e=>void inspect(e.target.files?.[0]||null)}/>{busy&&<div className="loading-text">Đang kiểm tra file…</div>}{error&&<div className="toast error static-toast">{error}</div>}{preview&&<div className="import-preview"><strong>Đã kiểm tra: {preview.workers.length} công nhân · {preview.teams.length} tổ</strong><span>SHA-256: {hash.slice(0,16)}…</span><div className="import-team-list">{preview.teams.map(team=><span className="badge badge-navy" key={team}>{team}</span>)}</div><button className="btn btn-primary" disabled={busy} onClick={commit}>Xác nhận cập nhật danh sách & quỹ lương</button></div>}</div></div>;
}
